Can't use this script to get its own change log.

diff --git a/build/history/mkchangelogs b/build/history/mkchangelogs
--- a/build/history/mkchangelogs
+++ b/build/history/mkchangelogs
@@ -1,6 +1,6 @@
 ###############################################################################
 #
-# $Id: mkchangelogs,v 1.33 2005/04/05 20:58:29 tbingham Exp $ $Name:  $
+# $Id: mkchangelogs,v 1.34 2005/06/03 16:35:50 tbingham Exp $ $Name:  $
 #
 # The contents of this file are subject to the AAF SDK Public
 # Source License Agreement (the "License"); You may not use this file
@@ -113,6 +113,12 @@ cmfile=${2}
 if [[ ! -s $cmfile ]]
 then
   echo "$TOOLNAME : Can't find color map \"${cmfile}\"."
+  exit 1
+fi
+
+if [ $0 -ef ./build/history/mkchangelogs ]
+then
+  echo "$TOOLNAME : Can't use this script to get its own change log."
   exit 1
 fi
 
